version: '3.8'

services:
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8088:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - "start-dev"

  mail:
    image: maildev/maildev
    container_name: mail
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

  mysql:
    image: mysql:8
    container_name: mysql-containers
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: book_net
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3302:3306"
    networks:
      - spring-demo
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  keycloak-data:
    driver: local
